services:
  - type: web
    name: ai-image-upscaler
    env: python
    pythonVersion: 3.10.12       
    buildCommand: "pip install -r requirements.txt && python download_models.py"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: PORT
        value: 10000
    disks:
      - name: ai-upscaler-disk
        mountPath: /opt/render/project/src/weights
        sizeGB: 1
